# Generated by Django 3.2.9 on 2021-12-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leng',
            field=models.CharField(blank=True, choices=[('русский язык', 'русский язык'), ('украинский язык', 'украинский язык'), ('белорусский язык', 'белорусский язык'), ('английский язык', 'английский язык')], default='русский язык', max_length=25, verbose_name='язык'),
        ),
    ]
