# Generated by Django 3.2.9 on 2021-12-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_userprofile_leng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='leng',
            new_name='lang',
        ),
    ]
