# Generated by Django 3.2.9 on 2021-12-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_rename_leng_userprofile_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, default='Русский', max_length=25, verbose_name='язык'),
        ),
    ]
